language: node_js
node_js:
  - "node"
  - "8"
  - "7"

cache:
  directories:
    - "node_modules"

after_success: 'NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha \
  --require blanket \
  --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js'
